M48
; DRILL file {KiCad 9.0.1} date 2025-05-11T20:17:05+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-11T20:17:05+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.580
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.660
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.850
%
G90
G05
T2
X123.58Y-70.24
T3
X134.65Y-98.4
X134.65Y-107.4
T1
G00X130.87Y-70.24
M15
G01X131.29Y-70.24
M16
G05
M30
